---
# This playbook would deploy postgresql

- name: Include distribution variables
  include_vars:
    file: "../vars/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- name: Install postgresql server
  package:
    name: "{{postgresql_package}}"
    state: present

- name: Install psycopg2
  package:
    name: python-psycopg2
    state: present

- name: create pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{postgresql_version}}/{{postgresql_cluster_name}}/pg_hba.conf"
    owner: "{{postgresql_service_user}}"
    group: "{{postgresql_service_group}}"
    mode: 0640
  register: pg_hba

- name: enable postgresql
  systemd:
    name: postgresql
    state: restarted
    enabled: yes
  when: pg_hba | changed

- name: create db
  postgresql_db:
    name: "{{dlvm_db_name}}"
    login_user: "{{postgresql_admin_user}}"

- name: create db user
  postgresql_user:
    db: "{{dlvm_db_name}}"
    name: "{{dlvm_db_user}}"
    password: "{{dlvm_db_password}}"
    priv: ALL
    state: present
    login_user: "{{postgresql_admin_user}}"
