---
# This playbook would install all dlvm control plan components and
# mariadb, rabbitmq on a single server

- hosts: all
  roles:
    - role: mariadb
    - role: rabbitmq
    - role: api_server
    - role: worker
    - role: beat
