---
# This playbook would deploy celery monitor

- name: Create monitor workdir
  file:
    path: "{{monitor_workdir}}"
    state: directory
    owner: "{{dlvm_user}}"
    group: "{{dlvm_group}}"
    recurse: yes

- name: Create monitor service file
  template:
    src: monitor.service.j2
    dest: /etc/systemd/system/dlvm_monitor.service
  notify: "Restart monitor"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart monitor"
  when: dlvm_update.changed
