---
# This playbook would deploy dlvm_monitor

- name: Copy systemd unit
  template:
    src: dlvm_monitor.service.j2
    dest: /etc/systemd/system/dlvm_monitor.service

- name: Start dlvm_monitor service
  systemd:
    name: dlvm_monitor
    state: restarted
    daemon_reload: yes
    enabled: yes
