---
# This playbook would deploy dlvm_dpv_agent

- name: Include distribution variables
  include_vars:
    file: "../vars/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- name: Install system package
  package:
    name: "{{item}}"
    state: present
  with_items: "{{system_packages}}"

- name: Copy iscsi configure files
  template:
    src: "{{item}}.j2"
    dest: /etc/iscsi/{{item}}
  with_items:
    - initiatorname.iscsi
    - iscsid.conf
  notify:
    - restart iscsid
