---
# This playbook would deploy dlvm_dpv_agent

- include: DebianInstall.yml
  when: "ansible_os_family == 'Debian'"

- include: RedHatInstall.yml
  when: "ansible_os_family == 'RedHat'"

- name: Init dpv transaction number
  command: "/bin/bash -c 'source {{dlvm_env_path}}/bin/activate; dlvm_init_obt dpv 0'"
  become: yes
  become_user: "{{dlvm_user}}"

- name: Copy systemd unit
  template:
    src: dlvm_dpv_agent.service.j2
    dest: /usr/lib/systemd/system/dlvm_dpv_agent.service
  register: dpv_agent_service

- name: Reload systemd for dpv_agent service
  command: /usr/bin/systemctl --system daemon-reload
  when: dpv_agent_service | changed

- name: Start dlvm_dpv_agent service
  systemd:
    name: dlvm_dpv_agent
    state: restarted
    enabled: yes
