---
# This playbook would deploy dlvm_dpv_agent

- name: Include distribution variables
  include_vars:
    file: "../vars/{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- name: Install system package
  package:
    name: "{{item}}"
    state: present
  with_items: "{{system_packages}}"

- name: Init dpv transaction number
  command: "/bin/bash -c 'source {{dlvm_env_path}}/bin/activate; dlvm_init_obt dpv 0'"
  become: yes
  become_user: "{{dlvm_user}}"

- name: Copy systemd unit
  template:
    src: dlvm_dpv_agent.service.j2
    dest: /etc/systemd/system/dlvm_dpv_agent.service

- name: Start dlvm_dpv_agent service
  systemd:
    name: dlvm_dpv_agent
    state: restarted
    daemon_reload: yes
    enabled: yes
