---
# This playbook would deploy dlvm dpv agent

- name: Create dpv agent service file
  template:
    src: dpv_agent.service.j2
    dest: /etc/systemd/system/dlvm_dpv_agent.service
  notify: "Restart dpv_agent"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart dpv_agent"
  when: dlvm_update.changed
