---
# This playbook would deploy dlvm_thost_agent

- name: Init thost transaction number
  command: "/bin/bash -c 'source {{dlvm_env_path}}/bin/activate; dlvm_init_transaction thost 0'"
  become: yes
  become_user: "{{dlvm_user}}"

- name: Copy systemd unit
  template:
    src: dlvm_thost_agent.service.j2
    dest: /usr/lib/systemd/system/dlvm_thost_agent.service

- name: Start dlvm_thost_agent service
  systemd:
    name: dlvm_thost_agent
    state: restarted
    enabled: yes
