---
# This playbook would deploy dlvm_host_agent

- name: Install epel
  yum: name=epel-release state=present

- name: Install system packages
  yum: name="{{item}}" state=present
  with_items: "{{host_system_packages}}"

- name: Install iscsi-initiator-utils
  yum: name=iscsi-initiator-utils state=present

- name: Copy iscsi initaitor configure file and name file
  template: src="{{item}}.j2" dest=/etc/iscsi/{{item}}
  with_items: "{{iscsi_initiator_files}}"
  notify:
    - restart iscsid
    
- name: Create dlvm group
  group: name=dlvm

- name: Create dlvm user
  user: name=dlvm group=dlvm groups=wheel

- name: Copy dlvm sudo no passward file
  copy: src=99-dlvm-user dest=/etc/sudoers.d/99-dlvm-user

- name: Create dlvm log directory
  file: path="/var/log/dlvm" state=directory owner=dlvm group=dlvm recurse=yes

- name: Checkout dlvm_host_agent
  git:
    repo=https://github.com/dlvm/dlvm_host_agent.git
    dest=/opt/dlvm_host_agent
    version={{host_version}}

- name: Install pip
  yum: name=python-pip state=present

- name: Install virtualenv
  pip: name=virtualenv

- name: Create virtualenv and install dlvm_host_agent
  pip:
    requirements="/opt/dlvm_host_agent/requirements.txt"
    virtualenv="/opt/dlvm_host_agent_env"
    virtualenv_python=python2.7

- name: Install dlvm_host_agent
  pip:
    name="file:///opt/dlvm_host_agent"
    virtualenv="/opt/dlvm_host_agent_env"
    state=latest
  notify:
    - restart dlvm_host_agent

- name: Copy configure templates
  template: src="{{item}}.j2" dest=/etc/dlvm/{{item}}
  with_items: "{{host_configure_files}}"
  notify:
    - restart dlvm_host_agent

- name: Copy systemd unit
  copy:
    src=dlvm_host_agent.service
    dest=/usr/lib/systemd/system/dlvm_host_agent.service

- name: Start dlvm_host_agent service
  service: name=dlvm_host_agent state=started enabled=yes
  register: dpv_host_service

- name: Reload systemd
  command: /usr/bin/systemctl --system daemon-reload
  when: dpv_host_service | changed
