---
# This playbook would deploy dlvm_ihost_agent

- name: Init ihost transaction number
  command: "/bin/bash -c 'source {{dlvm_env_path}}/bin/activate; dlvm_init_obt ihost 0'"
  become: yes
  become_user: "{{dlvm_user}}"

- name: Makesure ihost local obt db permission
  file:
    path: "{{dlvm_conf.work_dir}}"
    state: directory
    recurse: yes
    owner: "{{dlvm_user}}"
    group: "{{dlvm_group}}"

- name: Copy systemd unit
  template:
    src: dlvm_ihost_agent.service.j2
    dest: /etc/systemd/system/dlvm_ihost_agent.service

- name: Start dlvm_ihost_agent service
  systemd:
    name: dlvm_ihost_agent
    state: restarted
    daemon_reload: yes
    enabled: yes
