---
# This playbook would deploy dlvm ihost agent

- name: Create ihost agent service file
  template:
    src: ihost_agent.service.j2
    dest: /etc/systemd/system/dlvm_ihost_agent.service
  notify: "Restart ihost_agent"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart ihost_agent"
  when: dlvm_update.changed
