---
# This playbook would deploy dlvm api server

- name: Init db
  command: "/bin/bash -c 'source {{dlvm_env_path}}/bin/activate; export DLVM_CONF={{dlvm_conf_path}}; dlvm_init_db'"
  become: yes
  become_user: "{{dlvm_user}}"

- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{dlvm_env_path}}"
    state: present
  notify: "Restart gunicorn"

- name: Create gunicorn service file
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/dlvm_gunicorn.service
  notify: "Restart gunicorn"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart gunicorn"
  when: dlvm_update.changed
