---
# This playbook would deploy dlvm api server

- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{dlvm_env_path}}"
    state: present
  notify: "Restart gunicorn"

- name: Create gunicorn service file
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  notify: "Restart gunicorn"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart gunicorn"
  when: dlvm_update.changed
