---
# This playbook would deploy dlvm api server

- name: Init db
  command: "/bin/bash -c 'source {{dlvm_env_path}}/bin/activate; dlvm_init_db'"
  become: yes
  become_user: "{{dlvm_user}}"

- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{dlvm_env_path}}"
    state: latest

- name: Create gunicorn service file
  template:
    src: gunicorn.service.j2
    dest: /usr/lib/systemd/system/gunicorn.service

- name: Start gunicorn
  systemd:
    name: gunicorn
    state: restarted
    enabled: yes
