---
# This playbook would deploy dlvm worker

- name: Create celery service file
  template:
    src: celery.service.j2
    dest: /etc/systemd/system/dlvm_celery.service
  notify: "Restart celery"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart celery"
  when: dlvm_update.changed
