---
# This playbook would install dlvm package

- name: Install python3
  include: "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- name: Create dlvm group
  group:
    name: "{{dlvm_group}}"
    state: present

- name: Create dlvm user
  user:
    name: "{{dlvm_user}}"
    group: "{{dlvm_group}}"
    state: present

- name: Configure sudo
  template:
    src: 80-dlvm-user.j2
    dest: /etc/sudoers.d/80-dlvm-user
