---
# Install dlvm on redhat

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no


- name: Install system package
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - python-pip
    - libselinux-python
