---
# This playbook would deploy celery beat

- name: Create beat workdir
  file:
    path: "{{beat_workdir}}"
    state: directory
    owner: "{{dlvm_user}}"
    group: "{{dlvm_group}}"
    recurse: yes

- name: Create beat service file
  template:
    src: beat.service.j2
    dest: /etc/systemd/system/dlvm_beat.service
  notify: "Restart beat"

- name: Check dlvm_update
  command: /bin/true
  notify: "Restart beat"
  when: dlvm_update.changed
